version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: ooshieph9aechoo2Yai5cahchei2zohceic0Su5chi9hoGhuc7chi8Heighu2nae
serial:
  rtscts: false
  port: tcp://Dongle-M.local:6638
  adapter: ember
  baudrate: 115200
advanced:
  log_level: debug
  channel: 11
  network_key:
    - 244
    - 14
    - 221
    - 106
    - 81
    - 209
    - 191
    - 92
    - 144
    - 58
    - 20
    - 119
    - 250
    - 89
    - 249
    - 235
  pan_id: 616
  ext_pan_id:
    - 15
    - 20
    - 125
    - 219
    - 40
    - 113
    - 172
    - 127
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
  discovery_topic: homeassistant
devices:
  '0xa4c138b3073fd57a':
    friendly_name: sensor-movimento-corredor
  '0xa4c138077b1f9823':
    friendly_name: sensor-escada-02
  '0xa4c138fad35f10d2':
    friendly_name: sensor-escada-01
  '0xa4c138d88daec860':
    friendly_name: siren
  '0xa4c138c2f6cc5e9f':
    friendly_name: sensor-porta-escritorio
  '0x00158d008bef244f':
    friendly_name: Fechadura LIA
    expose_pin: true
  '0xa4c13885247efc8f':
    friendly_name: janela-quarto-criancas
  '0xa4c1385ac481695c':
    friendly_name: porta-da-sacada
  '0xa4c138f1e8300a08':
    friendly_name: sensor-porta-dos-fundos
  '0xa4c1385ac379cbc5':
    friendly_name: irrigacao
  '0x8c8b48fffe587802':
    friendly_name: energy-monitor
  '0xa4c1383f7c0d8f0a':
    friendly_name: '0xa4c1383f7c0d8f0a'
